In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv(r'C:\Users\DELL\Downloads\movies-db-small.csv')

**Reading the csv file**

In [3]:
df.head()

,genres,id,imdb_id,original_language,original_title,overview,production_companies,release_date,runtime,title,vote_average
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",30-10-1995,81.0,Toy Story,7.7
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",15-12-1995,104.0,Jumanji,6.9
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",22-12-1995,101.0,Grumpier Old Men,6.5
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",[{'name': 'Twentieth Century Fox Film Corporat...,22-12-1995,127.0,Waiting to Exhale,6.1
4,"[{'id': 35, 'name': 'Comedy'}]",11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'name': 'Sandollar Productions', 'id': 5842}...",10/2/1995,106.0,Father of the Bride Part II,5.7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15323 entries, 0 to 15322
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   genres                15323 non-null  object
 1   id                    15323 non-null  int64
 2   imdb_id               15318 non-null  object
 3   original_language     15323 non-null  object
 4   original_title        15323 non-null  object
 5   overview              15313 non-null  object
 6   production_companies  15322 non-null  object
 7   release_date          15309 non-null  object
 8   runtime               15322 non-null  float64
 9   title                 15322 non-null  object
 10  vote_average          15322 non-null  float64
dtypes: float64(2), int64(1), object(8)
memory usage: 1.3+ MB

**Showing missing values**

In [5]:
df.isnull().sum()

genres                   0
id                       0
imdb_id                  5
original_language        0
original_title           0
overview                10
production_companies     1
release_date            14
runtime                  1
title                    1
vote_average             1
dtype: int64

**Descending order by vote_average**

In [6]:
df.groupby('original_title')['vote_average'].mean().sort_values(ascending = False)

original_title
Ten Benny                                     10.0
Something in the Wind                         10.0
Dinosaurs!  A Fun-Filled Trip Back In Time    10.0
Joe Cocker - Mad Dogs & Englishmen            10.0
Girl in the Cadillac                          10.0
                                              ...
Hail Columbia!                                 0.0
All Access: Front Row. Backstage. Live!        0.0
Swedish Auto                                   0.0
Tender Comrade                                 0.0
Midnight Man                                   NaN
Name: vote_average, Length: 14743, dtype: float64

**How many movies have average rating above 5?**

In [7]:
df[df['vote_average'] > 5]['original_title'].count()

12552

**How many movies have average rating above 6?**

In [8]:
df[df['vote_average'] > 6]['original_title'].count()

8020

**How many movies have average rating above 7?**

In [9]:
df[df['vote_average'] > 7]['original_title'].count()

2353

**How many movies are in horror genre?**

In [10]:
df[df['vote_average'] > 7]['original_title'].count()

2353

In [11]:
df.groupby('original_title')['vote_average'].count().sort_values(ascending = False)

original_title
Hamlet                          7
The Three Musketeers            7
Alice in Wonderland             5
Jane Eyre                       4
Treasure Island                 4
                               ..
History of the World: Part I    1
Hit & Run                       1
Hit and Runway                  1
포화 속으로                          1
Midnight Man                    0
Name: vote_average, Length: 14743, dtype: int64

In [12]:
df.groupby('title')['vote_average'].mean()

title
!Women Art Revolution       4.3
$5 a Day                    6.0
$9.99                       6.0
'Neath the Arizona Skies    3.7
'R Xmas                     5.3
                           ...
xXx: State of the Union     4.7
¡Three Amigos!              6.3
À la mode                   0.0
Æon Flux                    5.4
’Round Midnight             6.7
Name: vote_average, Length: 14717, dtype: float64

In [13]:
df[['original_title','title']]

                    original_title                        title
0                        Toy Story                    Toy Story
1                          Jumanji                      Jumanji
2                 Grumpier Old Men             Grumpier Old Men
3                Waiting to Exhale            Waiting to Exhale
4      Father of the Bride Part II  Father of the Bride Part II
...                            ...                          ...
15318               The Juche Idea               The Juche Idea
15319               Wreck-It Ralph               Wreck-It Ralph
15320           Lookin' to Get Out           Lookin' to Get Out
15321             Diplomatic Siege             Diplomatic Siege
15322                 Midnight Man                          NaN

[15323 rows x 2 columns]

**Extracting genres from the list of dictionaries**

In [14]:
import ast

In [15]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
ast.literal_eval("[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]")

[{'id': 16, 'name': 'Animation'},
 {'id': 35, 'name': 'Comedy'},
 {'id': 10751, 'name': 'Family'}]

In [17]:
df['genres'] = df['genres'].apply(convert)

In [18]:
df.head(1)

,genres,id,imdb_id,original_language,original_title,overview,production_companies,release_date,runtime,title,vote_average
0,"[Animation, Comedy, Family]",862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]",30-10-1995,81.0,Toy Story,7.7

**Dropping unnecessary columns**

In [19]:
df.drop(['production_companies','release_date','runtime','original_title'], axis = 1,inplace = True)

In [20]:
df.head()

,genres,id,imdb_id,original_language,overview,title,vote_average
0,"[Animation, Comedy, Family]",862,tt0114709,en,"Led by Woody, Andy's toys live happily in his ...",Toy Story,7.7
1,"[Adventure, Fantasy, Family]",8844,tt0113497,en,When siblings Judy and Peter discover an encha...,Jumanji,6.9
2,"[Romance, Comedy]",15602,tt0113228,en,A family wedding reignites the ancient feud be...,Grumpier Old Men,6.5
3,"[Comedy, Drama, Romance]",31357,tt0114885,en,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale,6.1
4,[Comedy],11862,tt0113041,en,Just when George Banks has recovered from his ...,Father of the Bride Part II,5.7

**Converting list into string of genre column**

In [21]:
df['genres'] = df['genres'].apply(lambda x:[i.replace(" ","") for i in x])

In [22]:
df['genres'] = df['genres'].apply(lambda x:" ".join(x))

In [23]:
df['genres']

0                  Animation Comedy Family
1                 Adventure Fantasy Family
2                           Romance Comedy
3                     Comedy Drama Romance
4                                   Comedy
                       ...
15318
15319    Family Animation Comedy Adventure
15320                               Comedy
15321                      Action Thriller
15322                Action Thriller Drama
Name: genres, Length: 15323, dtype: object

**Creating a column named 'tags' on the basis of which we will recommend movies**

In [24]:
df['tags'] = df['genres'] +" " + df['overview']

In [25]:
df['tags']

0        Animation Comedy Family Led by Woody, Andy's t...
1        Adventure Fantasy Family When siblings Judy an...
2        Romance Comedy A family wedding reignites the ...
3        Comedy Drama Romance Cheated on, mistreated an...
4        Comedy Just when George Banks has recovered fr...
                               ...
15318     Jim Finn, follows a South Korean video artist...
15319    Family Animation Comedy Adventure Wreck-It Ral...
15320    Comedy Two gamblers must leave New York City a...
15321    Action Thriller When Steve Mitchell is clandes...
15322    Action Thriller Drama British soldiers force a...
Name: tags, Length: 15323, dtype: object

**Dropping unnecessary columns and null values**

In [26]:
df.drop('imdb_id',axis =1, inplace= True)

In [27]:
df.drop(['original_language','genres','overview'],axis =1, inplace= True)

In [28]:
df.dropna(inplace = True)

In [29]:
df.isnull().sum()

id              0
title           0
vote_average    0
tags            0
dtype: int64

**Converting object to string in 'tags' column**

In [30]:
df['tags'].dtypes

dtype('O')

In [31]:
df['tags'].apply(lambda x: str(x))

0        Animation Comedy Family Led by Woody, Andy's t...
1        Adventure Fantasy Family When siblings Judy an...
2        Romance Comedy A family wedding reignites the ...
3        Comedy Drama Romance Cheated on, mistreated an...
4        Comedy Just when George Banks has recovered fr...
                               ...
15317    Drama Seventeen-year-old Shirley (Katherine Wa...
15318     Jim Finn, follows a South Korean video artist...
15319    Family Animation Comedy Adventure Wreck-It Ral...
15320    Comedy Two gamblers must leave New York City a...
15321    Action Thriller When Steve Mitchell is clandes...
Name: tags, Length: 15312, dtype: object

**Making all the values to lower case of 'tags' column**

In [32]:
def lowercase_tags(x):
    if isinstance(x, str):
        return x.lower()
    else:
        return x

In [33]:
df['tags'] = df['tags'].apply(lowercase_tags)

In [34]:
df['tags']

0        animation comedy family led by woody, andy's t...
1        adventure fantasy family when siblings judy an...
2        romance comedy a family wedding reignites the ...
3        comedy drama romance cheated on, mistreated an...
4        comedy just when george banks has recovered fr...
                               ...
15317    drama seventeen-year-old shirley (katherine wa...
15318     jim finn, follows a south korean video artist...
15319    family animation comedy adventure wreck-it ral...
15320    comedy two gamblers must leave new york city a...
15321    action thriller when steve mitchell is clandes...
Name: tags, Length: 15312, dtype: object

**Converting tags into vectors**

In [35]:
#Basically we are putting words into numbers
#We are extracting 5000 words from all the description concatenated together and
#we are excluding the stop_words(i.e. 'a','is','from','are','to',etc.)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [36]:
vectors = cv.fit_transform(df['tags']).toarray()

In [37]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
cv.get_feature_names()

C:\Anaconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1920s',
 '1930s',
 '1940',
 '1940s',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1957',
 '1959',
 '1960',
 '1960s',
 '1964',
 '1965',
 '1966',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1980',
 '1980s',
 '1986',
 '1987',
 '1990',
 '1994',
 '1996',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2008',
 '2009',
 '20th',
 '21',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '28',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '50',
 '500',
 '50s',
 '60',
 '60s',
 '70',
 '70s',
 '80',
 '80s',
 'aaron',
 'abandoned',
 'abandons',
 'abducted',
 'abducts',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abroad',
 'absence',
 'absent',
 'abuse',
 'abused',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accidents',
 'acclaimed',
 'accompanied',
 'accompany',
 'according',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'acquaintance',
 'act',
 'acting',
 'action',
 'actions',
 'active',
 'activist',
 'activities',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'ad',
 'adam',
 'adams',
 'adaptation',
 'adapted',
 'add',
 'addict',
 'addicted',
 'addiction',
 'addition',
 'adds',
 'adjust',
 'administration',
 'admiral',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adult',
 'adulthood',
 'adults',
 'advanced',
 'advances',
 'advantage',
 'adventure',
 'adventurer',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affected',
 'affection',
 'affections',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftermath',
 'afternoon',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'ages',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'aircraft',
 'airline',
 'airplane',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'album',
 'alcohol',
 'alcoholic',
 'alec',
 'alex',
 'alexander',
 'alfred',
 'ali',
 'alice',
 'alien',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allison',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alter',
 'altered',
 'alternate',
 'alternative',
 'amanda',
 'amateur',
 'amazing',
 'amazon',
 'ambassador',
 'ambition',
 'ambitions',
 'ambitious',
 'amelia',
 'america',
 'american',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amusement',
 'amy',
 'ancient',
 'anderson',
 'andrew',
 'andrews',
 'andy',
 'angel',
 'angela',
 'angeles',
 'angels',
 'anger',
 'angie',
 'angry',
 'animal',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'anne',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymous',
 'answer',
 'answers',
 'anthony',
 'anti',
 'antics',
 'antonio',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyptic',
 'apollo',
 'apparent',
 'apparently',
 'appeal',
 'appear',
 'appearance',
 'appearances',
 'appeared',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approached',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'archie',
 'architect',
 'archival',
 'archive',
 'arctic',
 'area',
 'aren',
 'arise',
 'aristocrat',
 'aristocratic',
 'arizona',
 'arkansas',
 'arm',
 'armed',
 'arms',
 'armstrong',
 'army',
 'arnold',
 'arrange',
 'arranged',
 'arranges',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspects',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistance',
 'assistant',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'athletic',
 'atlantic',
 'atomic',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempted',
 'attempting',
 'attempts',
 'attend',
 'attendant',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attitudes',
 'attorney',
 'attract',
 'attracted',
 'attraction',
 'attractive',
 'attracts',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austrian',
 'author',
 'authorities',
 'authority',
 'auto',
 'autobiographical',
 'automobile',
 'available',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'awards',
 'aware',
 'away',
 'awkward',
 'awry',
 'babe',
 'babies',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'backstage',
 'backyard',
 'bad',
 'badly',
 'bag',
 'baker',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandit',
 'bandits',
 'bands',
 'bank',
 'banker',
 'banks',
 'bar',
 'barbara',
 'barely',
 'bargained',
 'barney',
 'baron',
 'barry',
 'bars',
 'bart',
 'base',
 'baseball',
 'based',
 'basement',
 'basis',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bay',
 'bbc',
 'beach',
 'bear',
 'bears',
 'beast',
 'beat',
 'beaten',
 'beating',
 'beau',
 'beautiful',
 'beauty',
 'bed',
 'bedroom',
 'beer',
 'befriended',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'begun',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'bella',
 'belle',
 'belong',
 'beloved',
 'ben',
 'beneath',
 'benjamin',
 'bennett',
 'benson',
 'bent',
 'berlin',
 'bernard',
 'bernie',
 'berry',
 'best',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bets',
 'better',
 'betty',
 'beverly',
 'bianca',
 'bible',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikers',
 'billionaire',
 'bills',
 'billy',
 'biographical',
 'biography',
 'biological',
 'biopic',
 'bird',
 'birds',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blackmail',
 'blake',
 'blame',
 'blind',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'blossoms',
 'blow',
 'blows',
 'blue',
 'blues',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobby',
 'bodies',
 'body',
 'bodyguard',
 'bogart',
 'bold',
 'bomb',
 'bomber',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'bones',
 'bonnie',
 'book',
 'books',
 'booze',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'bound',
 'boundaries',
 'bounty',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'brad',
 'bradley',
 'brain',
 'brand',
 'brandon',
 'brash',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breed',
 'brenda',
 'brian',
 'bride',
 'bridge',
 'bridges',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'bronx',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruno',
 'brutal',
 'brutally',
 'buck',
 'bud',
 'buddies',
 'budding',
 'buddy',
 'budget',
 'bugs',
 'build',
 'building',
 'builds',
 'built',
 'bull',
 'bullet',
 'bullies',
 'bully',
 'bumbling',
 'bunch',
 'bunny',
 'buried',
 'burn',
 'burned',
 'burning',
 'burns',
 'burt',
 'burton',
 'bury',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'buster',
 'busy',
 'butler',
 'buy',
 'buying',
 'buys',
 'cab',
 'cabin',
 'cable',
 'cagney',
 'caine',
 'california',
 'called',
 'calling',
 'calls',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'cameron',
 'camp',
 'campaign',
 'campbell',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'capturing',
 'car',
 'card',
 'cards',
 'care',
 'career',
 'careers',
 'carefree',
 'cares',
 'caretaker',
 'cargo',
 'caribbean',
 'caring',
 'carl',
 'carla',
 'carlos',
 'carmen',
 'carnival',
 'carol',
 'carolina',
 'carpenter',
 'carrie',
 'carries',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'cases',
 'casey',
 'cash',
 'casino',
 'cast',
 'casting',
 'castle',
 'casts',
 'cat',
 'catastrophe',
 'catch',
 'catches',
 'catherine',
 'catholic',
 'cathy',
 'cats',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cecil',
 'celebrate',
 'celebrated',
 'celebrating',
 'celebration',
 'celebrity',
 'cell',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'certainly',
 'chain',
 'chair',
 'challenge',
 'challenged',
 'challenges',
 'challenging',
 'champ',
 'champion',
 'championship',
 'chance',
 'chances',
 'change',
 'changed',
 'changes',
 'changing',
 'channel',
 'chaos',
 'character',
 'characters',
 'charge',
 'charged',
 'charges',
 'charismatic',
 'charles',
 'charley',
 'charlie',
 'charlotte',
 'charm',
 'charming',
 'charms',
 'chase',
 'chased',
 'chases',
 'chasing',
 'chauffeur',
 'cheap',
 'cheating',
 'check',
 'cheerleader',
 'chef',
 'chelsea',
 'chemical',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'choice',
 'choices',
 'choose',
 'chooses',
 'chorus',
 'chosen',
 'chris',
 'christ',
 'christian',
 'christina',
 'christine',
 'christmas',
 'christopher',
 'chronicle',
 'chronicles',
 'chronicling',
 'chuck',
 'church',
 'cia',
 'cindy',
 'cinema',
 'cinematic',
 'circa',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizen',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'clad',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claude',
 'claus',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'clifford',
 'climax',
 'climb',
 'climbing',
 'clinic',
 'clint',
 'clips',
 'clock',
 'clone',
 'close',
 'closed',
 'closer',
 'closes',
 'closest',
 'closing',
 'clothes',
 'clouseau',
 'clown',
 'club',
 'clubs',
 'clue',
 'clues',
 'clutches',
 'coach',
 'coal',
 'coast',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffee',
 'coin',
 'col',
 'cold',
 'cole',
 'colin',
 'collapse',
 'collar',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colonel',
 'colonial',
 'color',
 'colorado',
 'colorful',
 'columbia',
 'com',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comfort',
 'comfortable',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commanding',
 'commentary',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'committing',
 'common',
 'communicate',
 'communist',
 'community',
 'companies',
 'companion',
 'companions',
 'company',
 'compelling',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'concentration',
 'concerned',
 'concerns',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'conduct',
 'confederate',
 'confidence',
 'confident',
 'conflict',
 'conflicts',
 'confront',
 'confrontation',
 'confronted',
 'confronts',
 'confused',
 'confusion',
 'connect',
 'connected',
 'connecticut',
 'connection',
 'connections',
 ...]

**Removing similar looking words from the features using Natural Language Toolkit**

In [39]:
import nltk

In [40]:
#The PorterStemmer do the thing which we want(i.e. it truncate things)
##['loving','loved','love'] to ['love','love','love']

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [41]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [42]:
df['tags'][0]

"animation comedy family led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences."

In [43]:
df['tags'] = df['tags'].apply(stem)

**Again repeating the steps**

In [44]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [45]:
vectors = cv.fit_transform(df['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
cv.get_feature_names()

['000',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1900',
 '1917',
 '1920',
 '1930',
 '1930s',
 '1933',
 '1934',
 '1935',
 '1939',
 '1940',
 '1940s',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1951',
 '1955',
 '1956',
 '1957',
 '1959',
 '1960',
 '1960s',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1981',
 '1984',
 '1985',
 '1986',
 '1987',
 '1989',
 '1990',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '20th',
 '21',
 '21st',
 '22',
 '23',
 '24',
 '25',
 '28',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 '90',
 'aaron',
 'abandon',
 'abduct',
 'abil',
 'abilities',
 'abl',
 'aboard',
 'abound',
 'abov',
 'abraham',
 'abroad',
 'absence',
 'absent',
 'absolut',
 'absorb',
 'absurd',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'accord',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'actions',
 'activ',
 'activist',
 'activities',
 'actor',
 'actors',
 'actress',
 'actual',
 'ad',
 'adam',
 'adams',
 'adapt',
 'add',
 'addict',
 'addit',
 'address',
 'adjust',
 'administr',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adult',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advice',
 'advis',
 'advoc',
 'affair',
 'affect',
 'affection',
 'afflict',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftermath',
 'afternoon',
 'afterward',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'aging',
 'ago',
 'agre',
 'agreement',
 'agrees',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'aircraft',
 'airlin',
 'airplan',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'album',
 'alcohol',
 'alec',
 'alex',
 'alexand',
 'alfr',
 'ali',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alike',
 'aliv',
 'alive',
 'allegedli',
 'allen',
 'alli',
 'allianc',
 'allison',
 'allow',
 'allur',
 'alon',
 'alongsid',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amanda',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambush',
 'amelia',
 'america',
 'american',
 'americans',
 'ami',
 'amid',
 'amidst',
 'amish',
 'amnesia',
 'amor',
 'amp',
 'amus',
 'amy',
 'analyst',
 'ancestor',
 'ancient',
 'anderson',
 'andi',
 'andr',
 'andrea',
 'andrew',
 'andy',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angi',
 'angri',
 'ani',
 'anim',
 'animals',
 'ann',
 'anna',
 'anne',
 'anni',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'anthoni',
 'anthropologist',
 'anti',
 'antic',
 'antics',
 'antiqu',
 'anton',
 'antonio',
 'anyon',
 'anyth',
 'apach',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalypt',
 'apollo',
 'appar',
 'appeal',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'approach',
 'approv',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'archi',
 'architect',
 'archiv',
 'arctic',
 'area',
 'aren',
 'arena',
 'argu',
 'aris',
 'aristocrat',
 'arizona',
 'arm',
 'armi',
 'armor',
 'armstrong',
 'army',
 'arnold',
 'arrang',
 'arrest',
 'arrested',
 'arriv',
 'arrival',
 'arrive',
 'arrives',
 'arrog',
 'art',
 'artagnan',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artist',
 'artists',
 'ash',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'assur',
 'astronaut',
 'asylum',
 'athlet',
 'atlant',
 'atmospher',
 'atom',
 'attach',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attention',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austrian',
 'author',
 'auto',
 'autobiograph',
 'automobil',
 'avail',
 'aveng',
 'averag',
 'aviat',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'axel',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backyard',
 'bad',
 'bag',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bankrupt',
 'bar',
 'barbara',
 'barber',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barren',
 'barri',
 'bars',
 'bart',
 'bas',
 'base',
 'basebal',
 'basement',
 'basic',
 'basketbal',
 'bat',
 'batman',
 'battl',
 'battle',
 'baxter',
 'bay',
 'bbc',
 'beach',
 'bean',
 'bear',
 'beast',
 'beat',
 'beaten',
 'beatl',
 'beau',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'beck',
 'becom',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'begun',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'bend',
 'beneath',
 'benefactor',
 'benefit',
 'benjamin',
 'bennett',
 'benson',
 'bent',
 'berlin',
 'bernard',
 'besid',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'better',
 'betti',
 'beverli',
 'bianca',
 'bibl',
 'biblic',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'billi',
 'billion',
 'billionair',
 'billy',
 'biograph',
 'biographi',
 'biolog',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blake',
 'blame',
 'blaze',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blown',
 'blue',
 'blur',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bobby',
 'bodi',
 'bodies',
 'body',
 'bodyguard',
 'bogart',
 'bold',
 'bomb',
 'bomber',
 'bond',
 'bone',
 'book',
 'books',
 'boom',
 'boost',
 'boot',
 'booth',
 'booz',
 'border',
 'bore',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bottl',
 'bought',
 'bounc',
 'bound',
 'boundari',
 'bounti',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boyhood',
 'boys',
 'brad',
 'bradley',
 'brain',
 'brand',
 'brandon',
 'brash',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breakup',
 'breath',
 'breed',
 'brenda',
 'brian',
 'brick',
 'bride',
 'bridg',
 'bridge',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'bronx',
 'brood',
 'brook',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruno',
 'brutal',
 'bu',
 'bubbl',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'bug',
 'build',
 'building',
 'built',
 'bull',
 'bullet',
 'bulli',
 'bully',
 'bum',
 'bumbl',
 'bunch',
 'burglar',
 'buri',
 'burk',
 'burn',
 'burt',
 'burton',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'buster',
 'butcher',
 'butler',
 'butt',
 'buy',
 'cab',
 'cabin',
 'cabl',
 'cagney',
 'cain',
 'cal',
 'calcul',
 'california',
 'calm',
 'calvin',
 'came',
 'camelot',
 'camera',
 'cameraman',
 'cameron',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannib',
 'canyon',
 'capabl',
 'cape',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captor',
 'captur',
 'captured',
 'car',
 'card',
 'cardin',
 'care',
 'career',
 'carefre',
 'caretak',
 'carey',
 'cargo',
 'caribbean',
 'carl',
 'carla',
 'carlo',
 'carmen',
 'carniv',
 'carol',
 'carolina',
 'carri',
 'cars',
 'carson',
 'cartel',
 'carter',
 'cartoon',
 'case',
 'casey',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'casual',
 'cat',
 'catastroph',
 'catch',
 'catherin',
 'catherine',
 'cathol',
 'cattl',
 'caught',
 'caus',
 'cause',
 'cavalri',
 'cave',
 'cecil',
 'celebr',
 'cell',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'certainli',
 'chagrin',
 'chain',
 'chair',
 'challeng',
 'chamber',
 'champ',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chaney',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charge',
 'charismat',
 'charl',
 'charles',
 'charley',
 'charli',
 'charlie',
 'charlott',
 'charm',
 'charming',
 'chart',
 'chase',
 'chauffeur',
 'cheap',
 'cheat',
 'check',
 'cheer',
 'cheerlead',
 'chef',
 'chelsea',
 'chemic',
 'chess',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'choic',
 'choice',
 'choos',
 'choru',
 'chosen',
 'chri',
 'chris',
 'christ',
 'christian',
 'christin',
 'christina',
 'christma',
 'christmas',
 'christoph',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cindi',
 'cinema',
 'cinemat',
 'circa',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'circus',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'clad',
 'claim',
 'clair',
 'claire',
 'clan',
 'clara',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classmates',
 'clau',
 'claud',
 'claus',
 'clay',
 'clean',
 'clear',
 'clearli',
 'clerk',
 'cleveland',
 'clever',
 'client',
 'clients',
 'cliff',
 'clifford',
 'climax',
 'climb',
 'clinic',
 'clint',
 'clip',
 'clock',
 'clone',
 'close',
 'closer',
 'closest',
 'closet',
 'cloth',
 'cloud',
 'clouseau',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'clyde',
 'coach',
 'coal',
 'coast',
 'coastal',
 'cocain',
 'cocki',
 'code',
 'coffe',
 'coin',
 'col',
 'cold',
 'cole',
 'colin',
 'collabor',
 'collaps',
 'collar',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collin',
 'collins',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbia',
 'com',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'command',
 'commander',
 'commando',
 'comment',
 'commentari',
 'commerci',
 'commiss',
 'commit',
 'commitment',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compar',
 'compel',
 'compet',
 'competit',
 'competition',
 'compil',
 'complet',
 'complex',
 'complic',
 'complicated',
 'compos',
 'compromis',
 'compuls',
 'comput',
 'computer',
 'comrad',
 'conan',
 'conceal',
 'conceiv',
 'concentr',
 'concept',
 'concern',
 'concert',
 'conclusion',
 'concoct',
 ...]

**Looking for similar vectors based on angles instead of distances**

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity = cosine_similarity(vectors)

In [50]:
similarity.shape

(15312, 15312)

In [51]:
sorted(list(enumerate(similarity[0])),reverse = True,key = lambda x:x[1])[1:6]

[(2680, 0.4116934847963092),
 (6297, 0.3380617018914067),
 (13689, 0.3265986323710904),
 (12298, 0.31754264805429416),
 (4273, 0.31622776601683794)]

In [52]:
similarity[1]

array([0.06918984, 1.        , 0.07617551, ..., 0.27962741, 0.        ,
       0.04007219])

**Finally defining a function that gives the movie recommendation based on what movie we are giving as input**

In [53]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True, key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [59]:
recommend('Batman Forever')

Batman & Robin
The Dark Knight Rises
Batman
Batman: Mask of the Phantasm
Batman Returns

In [55]:
import pickle

In [56]:
with open('movies_dict.pkl', 'wb') as file:
    pickle.dump(df.to_dict(), file)

In [57]:
with open('similarity.pkl', 'wb') as file:
    pickle.dump(similarity, file)